---@class KeyTrailConfig
---@field hover_delay? number The delay in milliseconds before showing the popup
---@field popup_highlight? string|table Highlight configuration for the popup background
---@field winblend? number Window transparency for the popup (0-100) (deprecated in favour of popup.winblend)
---@field popup? { enabled?: boolean, winblend?: number } Popup rendering options
---@field statusline? { enabled?: boolean, prefix?: string, suffix?: string, empty?: string } Statusline rendering options
---@field colors? string[] Array of colors to use for path segments
---@field delimiter? string The delimiter to use between path segments
---@field position? 'top'|'bottom' The position of the popup
---@field zindex? number The z-index of the popup window
---@field bracket_color? string The color for array brackets
---@field delimiter_color? string The color for the delimiter
---@field filetypes? table<string, boolean> Supported file types
---@field key_mapping? string

---@class KeyTrail
---@field setup fun(opts?: KeyTrailConfig) Setup the plugin with optional configuration
---@field handle_cursor_move fun() Handle cursor movement
---@field handle_window_change fun() Handle window changes
---@field handle_buffer_change fun() Handle buffer changes
